import Head from 'next/head';
import Image from 'next/image';

function Homez() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="underline">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}

import About from './Home/About';
import Contact from './Home/Contact';
import Projects from './Home/Projects';
import Welcome from './Home/Welcome';

function Home() {
  return (
    <div className="relative z-index-1">
      <Welcome />
      <About />
      <Projects />
      <Contact />
    </div>
  );
}

export default Home;
